/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsTopicIdRouteImport } from './routes/topics.$topicId'
import { Route as PasswordResetCompleteRouteImport } from './routes/password.reset-complete'
import { Route as PasswordResetRouteImport } from './routes/password.reset'
import { Route as PasswordForgotRouteImport } from './routes/password.forgot'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'
import { Route as AiAuthorizeRouteImport } from './routes/ai.authorize'
import { Route as TopicsTopicIdNewRouteImport } from './routes/topics.$topicId_.new'
import { Route as MemosMemoIdHistoryRouteImport } from './routes/memos.$memoId.history'
import { Route as DocumentsDocumentIdHistoryRouteImport } from './routes/documents.$documentId_.history'
import { Route as DocumentsDocumentIdEditRouteImport } from './routes/documents.$documentId_.edit'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetCompleteRoute = PasswordResetCompleteRouteImport.update({
  id: '/password/reset-complete',
  path: '/password/reset-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotRoute = PasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAuthorizeRoute = AiAuthorizeRouteImport.update({
  id: '/ai/authorize',
  path: '/ai/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdNewRoute = TopicsTopicIdNewRouteImport.update({
  id: '/topics/$topicId_/new',
  path: '/topics/$topicId/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosMemoIdHistoryRoute = MemosMemoIdHistoryRouteImport.update({
  id: '/memos/$memoId/history',
  path: '/memos/$memoId/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdHistoryRoute =
  DocumentsDocumentIdHistoryRouteImport.update({
    id: '/documents/$documentId_/history',
    path: '/documents/$documentId/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsDocumentIdEditRoute = DocumentsDocumentIdEditRouteImport.update({
  id: '/documents/$documentId_/edit',
  path: '/documents/$documentId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRoute
  '/trash': typeof TrashRoute
  '/ai/authorize': typeof AiAuthorizeRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/password/reset-complete': typeof PasswordResetCompleteRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/topics/': typeof TopicsIndexRoute
  '/documents/$documentId/edit': typeof DocumentsDocumentIdEditRoute
  '/documents/$documentId/history': typeof DocumentsDocumentIdHistoryRoute
  '/memos/$memoId/history': typeof MemosMemoIdHistoryRoute
  '/topics/$topicId/new': typeof TopicsTopicIdNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRoute
  '/trash': typeof TrashRoute
  '/ai/authorize': typeof AiAuthorizeRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/password/reset-complete': typeof PasswordResetCompleteRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/topics': typeof TopicsIndexRoute
  '/documents/$documentId/edit': typeof DocumentsDocumentIdEditRoute
  '/documents/$documentId/history': typeof DocumentsDocumentIdHistoryRoute
  '/memos/$memoId/history': typeof MemosMemoIdHistoryRoute
  '/topics/$topicId/new': typeof TopicsTopicIdNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRoute
  '/trash': typeof TrashRoute
  '/ai/authorize': typeof AiAuthorizeRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/password/reset-complete': typeof PasswordResetCompleteRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/topics/': typeof TopicsIndexRoute
  '/documents/$documentId_/edit': typeof DocumentsDocumentIdEditRoute
  '/documents/$documentId_/history': typeof DocumentsDocumentIdHistoryRoute
  '/memos/$memoId/history': typeof MemosMemoIdHistoryRoute
  '/topics/$topicId_/new': typeof TopicsTopicIdNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/search'
    | '/settings'
    | '/signup'
    | '/timeline'
    | '/trash'
    | '/ai/authorize'
    | '/documents/$documentId'
    | '/password/forgot'
    | '/password/reset'
    | '/password/reset-complete'
    | '/topics/$topicId'
    | '/topics/'
    | '/documents/$documentId/edit'
    | '/documents/$documentId/history'
    | '/memos/$memoId/history'
    | '/topics/$topicId/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/search'
    | '/settings'
    | '/signup'
    | '/timeline'
    | '/trash'
    | '/ai/authorize'
    | '/documents/$documentId'
    | '/password/forgot'
    | '/password/reset'
    | '/password/reset-complete'
    | '/topics/$topicId'
    | '/topics'
    | '/documents/$documentId/edit'
    | '/documents/$documentId/history'
    | '/memos/$memoId/history'
    | '/topics/$topicId/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/search'
    | '/settings'
    | '/signup'
    | '/timeline'
    | '/trash'
    | '/ai/authorize'
    | '/documents/$documentId'
    | '/password/forgot'
    | '/password/reset'
    | '/password/reset-complete'
    | '/topics/$topicId'
    | '/topics/'
    | '/documents/$documentId_/edit'
    | '/documents/$documentId_/history'
    | '/memos/$memoId/history'
    | '/topics/$topicId_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TimelineRoute: typeof TimelineRoute
  TrashRoute: typeof TrashRoute
  AiAuthorizeRoute: typeof AiAuthorizeRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  PasswordForgotRoute: typeof PasswordForgotRoute
  PasswordResetRoute: typeof PasswordResetRoute
  PasswordResetCompleteRoute: typeof PasswordResetCompleteRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  DocumentsDocumentIdEditRoute: typeof DocumentsDocumentIdEditRoute
  DocumentsDocumentIdHistoryRoute: typeof DocumentsDocumentIdHistoryRoute
  MemosMemoIdHistoryRoute: typeof MemosMemoIdHistoryRoute
  TopicsTopicIdNewRoute: typeof TopicsTopicIdNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/reset-complete': {
      id: '/password/reset-complete'
      path: '/password/reset-complete'
      fullPath: '/password/reset-complete'
      preLoaderRoute: typeof PasswordResetCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/reset': {
      id: '/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/forgot': {
      id: '/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof PasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/authorize': {
      id: '/ai/authorize'
      path: '/ai/authorize'
      fullPath: '/ai/authorize'
      preLoaderRoute: typeof AiAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId_/new': {
      id: '/topics/$topicId_/new'
      path: '/topics/$topicId/new'
      fullPath: '/topics/$topicId/new'
      preLoaderRoute: typeof TopicsTopicIdNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos/$memoId/history': {
      id: '/memos/$memoId/history'
      path: '/memos/$memoId/history'
      fullPath: '/memos/$memoId/history'
      preLoaderRoute: typeof MemosMemoIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId_/history': {
      id: '/documents/$documentId_/history'
      path: '/documents/$documentId/history'
      fullPath: '/documents/$documentId/history'
      preLoaderRoute: typeof DocumentsDocumentIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId_/edit': {
      id: '/documents/$documentId_/edit'
      path: '/documents/$documentId/edit'
      fullPath: '/documents/$documentId/edit'
      preLoaderRoute: typeof DocumentsDocumentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TimelineRoute: TimelineRoute,
  TrashRoute: TrashRoute,
  AiAuthorizeRoute: AiAuthorizeRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  PasswordForgotRoute: PasswordForgotRoute,
  PasswordResetRoute: PasswordResetRoute,
  PasswordResetCompleteRoute: PasswordResetCompleteRoute,
  TopicsTopicIdRoute: TopicsTopicIdRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  DocumentsDocumentIdEditRoute: DocumentsDocumentIdEditRoute,
  DocumentsDocumentIdHistoryRoute: DocumentsDocumentIdHistoryRoute,
  MemosMemoIdHistoryRoute: MemosMemoIdHistoryRoute,
  TopicsTopicIdNewRoute: TopicsTopicIdNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
