import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createClient, type Client } from '@libsql/client';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { createFogServices } from '@repo/core/application/fog/services';
import { nodeSecretCrypto } from '@repo/core/adapters/fog/crypto';
import { migrateFog } from '@repo/core/adapters/fog/schema';
import { LibsqlFogUnitOfWork } from '@repo/core/adapters/fog/unitOfWork';
import { UuidV7Generator } from '@repo/core/application/ports/idGenerator';
import { dispatchResetEmails } from '@repo/core/application/fog/resetEmailDispatcher';
import type { AuthResult, FogServices, HumanActor } from '@repo/core/application/fog/types';
import type { GoogleIdentityPort } from '@repo/core/application/fog/accountPorts';
let dir:string, client:Client, second:Client, services:FogServices, parallel:FogServices, a:AuthResult;
let now:Date;
const clock={now:()=>now};
const password='independent-original-password';
const newPassword='independent-replacement-password';
const browserToken='independent_browser_token_1234567890';
const exchange=vi.fn<GoogleIdentityPort['exchange']>();
const make=(db:Client)=>createFogServices({unitOfWork:new LibsqlFogUnitOfWork(db),crypto:nodeSecretCrypto,clock,ids:UuidV7Generator,appUrl:'http://127.0.0.1:3000',googleIdentity:{authorizationUrl:i=>`https://identity.example/auth?${new URLSearchParams(i)}`,exchange},aiClients:[{id:'independent',name:'Verifier AI',redirectUris:['http://127.0.0.1/callback']}]});
beforeEach(async()=>{dir=await mkdtemp(path.join(os.tmpdir(),'fog-independent-p4b-'));client=createClient({url:`file:${dir}/test.db`});await client.execute('PRAGMA journal_mode=WAL');await client.execute('PRAGMA foreign_keys=ON');await client.execute('PRAGMA busy_timeout=5000');await migrateFog(client);second=createClient({url:`file:${dir}/test.db`});await second.execute('PRAGMA foreign_keys=ON');await second.execute('PRAGMA busy_timeout=5000');now=new Date('2026-09-05T14:00:00.000Z');exchange.mockReset();exchange.mockResolvedValue({subject:'independent-subject',email:'google@independent.example',emailVerified:true});services=await make(client);parallel=await make(second);a=await services.register({email:'owner@independent.example',password});});
afterEach(async()=>{second.close();client.close();await rm(dir,{recursive:true,force:true});});
const count=async(table:string)=>Number((await client.execute(`SELECT count(*) n FROM ${table}`)).rows[0]!.n);
async function begin(actor:HumanActor|null=a.user){return new URL((await services.beginGoogleAuth(actor,{browserToken,returnTo:'/settings'})).url).searchParams.get('state')!;}
const complete=(state:string)=>services.completeGoogleAuth(a.user,{browserToken,state,code:'code'});
async function queuedToken(){await services.requestPasswordReset({email:a.user.email});return new URL(String((await client.execute('SELECT reset_url FROM fog_reset_emails ORDER BY created_at DESC,id DESC LIMIT 1')).rows[0]!.reset_url)).searchParams.get('token')!;}
async function pendingGrant(){const r=await services.beginAiAuthorization({clientId:'independent',redirectUri:'http://127.0.0.1/callback',state:'s',codeChallenge:nodeSecretCrypto.pkceChallenge('v'.repeat(43)),codeChallengeMethod:'S256'});await services.getAiAuthorization(a.user,r.requestToken);await services.decideAiAuthorization(a.user,{requestToken:r.requestToken,allow:true});}

test('R19: password reset committed during provider exchange invalidates link before credential creation',async()=>{const token=await queuedToken();const state=await begin();exchange.mockImplementation(async()=>{await parallel.completePasswordReset({token,newPassword});return {subject:'independent-subject',email:'google@independent.example',emailVerified:true};});await expect(complete(state)).rejects.toMatchObject({code:'INVALID_GOOGLE_AUTH'});expect(await count('fog_google_credentials')).toBe(0);expect(await services.authenticate(a.token)).toBeNull();expect(await count('fog_google_requests')).toBe(0);});

test('R20: ordinary password changes through independent DB clients admit one old-password winner',async()=>{const candidates=[newPassword,'independent-second-password'];const results=await Promise.allSettled([services.changePassword(a.user,{currentPassword:password,newPassword:candidates[0]!}),parallel.changePassword(a.user,{currentPassword:password,newPassword:candidates[1]!})]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);const winner=results.findIndex(x=>x.status==='fulfilled');const auth=results[winner]!;if(auth.status!=='fulfilled')throw new Error('winner');expect(await count('fog_sessions')).toBe(1);expect(await services.authenticate(a.token)).toBeNull();expect(await services.authenticate(auth.value.token)).toEqual(a.user);expect((await services.login({email:a.user.email,password:candidates[winner]!})).user).toEqual(a.user);});

test('R20: reset session-insert fault restores password, sessions, pending grants, Google secrets, queued mail and tokens',async()=>{const token=await queuedToken();await begin();await pendingGrant();const tables=['fog_password_credentials','fog_sessions','fog_ai_authorization_requests','fog_ai_authorization_codes','fog_google_requests','fog_reset_emails','fog_password_resets','fog_account_recovery'];const snapshot=async()=>Promise.all(tables.map(async t=>(await client.execute(`SELECT * FROM ${t} ORDER BY rowid`)).rows));const before=await snapshot();await client.execute("CREATE TRIGGER verifier_session_fail BEFORE INSERT ON fog_sessions BEGIN SELECT RAISE(ABORT,'injected'); END");await expect(services.completePasswordReset({token,newPassword})).rejects.toMatchObject({code:'STORAGE_CONFLICT'});expect(await snapshot()).toEqual(before);expect(await services.authenticate(a.token)).toEqual(a.user);await client.execute('DROP TRIGGER verifier_session_fail');const reset=await services.completePasswordReset({token,newPassword});expect(await services.authenticate(reset.token)).toEqual(a.user);for(const t of tables.slice(2,7))expect(await count(t)).toBe(0);});

test('R20: late success/failure with an expired lease cannot delete or release a new worker lease',async()=>{await queuedToken();const work=new LibsqlFogUnitOfWork(client);const claim=(leaseToken:string)=>work.run(({account})=>account.claimResetMail({now:now.toISOString(),leaseUntil:new Date(now.getTime()+60000).toISOString(),leaseToken}));const first=await claim('first');expect(first).not.toBeNull();now=new Date(now.getTime()+60000);const next=await claim('second');expect(next?.id).toBe(first?.id);await work.run(async({account})=>{await account.deliveredResetMail(first!.id,'first');await account.retryResetMail({id:first!.id,leaseToken:'first',availableAt:now.toISOString()});});expect((await client.execute('SELECT lease_token,attempts FROM fog_reset_emails')).rows).toMatchObject([{lease_token:'second',attempts:2}]);await work.run(({account})=>account.deliveredResetMail(next!.id,'second'));expect(await count('fog_reset_emails')).toBe(0);});

test('R20: mailer I/O releases the transaction; reset while SMTP is in flight removes payload and leaves received URL unusable',async()=>{const token=await queuedToken();const sent=vi.fn(async()=>{await parallel.completePasswordReset({token,newPassword});expect(await count('fog_reset_emails')).toBe(0);});const output=await dispatchResetEmails({unitOfWork:new LibsqlFogUnitOfWork(client),clock,ids:UuidV7Generator,mailer:{sendPasswordReset:sent}});expect(output).toEqual({sentCount:1,failedCount:0});expect(sent).toHaveBeenCalledTimes(1);expect(await count('fog_reset_emails')).toBe(0);await expect(services.completePasswordReset({token,newPassword})).rejects.toMatchObject({code:'INVALID_RESET_TOKEN'});});
