config:
  fog-cf-resources:accountId: REPLACE_WITH_CF_ACCOUNT_ID
  fog-cf-resources:zoneName: example.com
  fog-cf-resources:appHostname: staging.example.com
  fog-cf-resources:appUrl: https://staging.example.com
  fog-cf-resources:resourcePrefix: fog-staging
