import { createLibsqlClient } from "../../packages/core/src/adapters/libsql/client";
import { nodeSecretCrypto } from "../../packages/core/src/adapters/fog/crypto";
import { migrateFog } from "../../packages/core/src/adapters/fog/schema";
import { LibsqlFogUnitOfWork } from "../../packages/core/src/adapters/fog/unitOfWork";
import { createFogServices } from "../../packages/core/src/application/fog/services";
import { UuidV7Generator } from "../../packages/core/src/application/ports/idGenerator";
const client=createLibsqlClient({url:"file:../../apps/web/data/app.db"});
await client.execute("PRAGMA journal_mode=WAL");await client.execute("PRAGMA foreign_keys=ON");await migrateFog(client);
const services=await createFogServices({unitOfWork:new LibsqlFogUnitOfWork(client),crypto:nodeSecretCrypto,clock:{now:()=>new Date()},ids:UuidV7Generator});
const email=`p3-owner-${Date.now()}@example.test`;
const {user:actor}=await services.register({email,password:"p3-local-password-2026"});
const topic=await services.createTopic(actor,{title:"P3 星雲の設計",description:"削除セットと出典を確認する"});
const destination=await services.createTopic(actor,{title:"P3 復元先",description:""});
const completed=await services.createTopic(actor,{title:"P3 完了した設計",description:"検索とexportに残る"});
await services.updateTopic(actor,{...completed,completed:true,expectedVersion:completed.version});
const memos=[];for(let i=0;i<65;i++)memos.push(await services.createMemo(actor,{body:`星雲のメモ ${String(i+1).padStart(2,"0")}。日本語検索をページングで確認する。`}));
const docs=[];for(let i=0;i<3;i++)docs.push(await services.createDocument(actor,{topicId:topic.id,title:`P3 星雲の文書${i+1}`,body:`# 星雲\n\n復元できる文書 ${i+1}`,sourceMemoIds:[memos[i].id],reason:"初稿"}));
await services.createDocument(actor,{topicId:completed.id,title:"星雲の完了文書",body:"完了しても検索できる。",sourceMemoIds:[],reason:"初稿"});
console.log(JSON.stringify({email,topic,destination,completed,memos:memos.map(({id,body})=>({id,body})),docs},null,2));client.close();
